# Generated by Django 5.1.6 on 2025-03-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hospital_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='specialties',
            field=models.JSONField(default=list),
        ),
    ]
